version: "3"
services:
  taxi_dash:
    build: .
    volumes:
      - /home/jay/pp_ny_taxi_dashboard/data/:/taxi_dash_dir/data/
    ports:
      - "8501:8501"
    env_file:
      - .env.example
    environment:
      - STREAMLIT_SERVER_HEADLESS=true