services:
  ui_service:
    build: .
    volumes:
      - /home/jay/pp_ny_taxi_dashboard/data/:/taxi_dash_dir/data/
      - /home/jay/pp_ny_taxi_dashboard/logs/:/taxi_dash_dir/logs/
    env_file: .env.example
    ports:
      - "8501:8501"
